// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

// @@protoc_insertion_point(imports)

@class ProtoInitKeySecretMessage;
@class ProtoInitKeySecretMessageBuilder;
@class ProtoKeyExchangeMessage;
@class ProtoKeyExchangeMessageBuilder;
@class ProtoSecretMessage;
@class ProtoSecretMessageBuilder;
@class ProtoSenderKeyDistributionMessage;
@class ProtoSenderKeyDistributionMessageBuilder;
@class ProtoSenderKeyMessage;
@class ProtoSenderKeyMessageBuilder;



@interface SecretTextProtocolRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define ProtoSecretMessage_coreKey @"coreKey"
#define ProtoSecretMessage_counter @"counter"
#define ProtoSecretMessage_previousCounter @"previousCounter"
#define ProtoSecretMessage_ciphertext @"ciphertext"
@interface ProtoSecretMessage : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasCoreKey_:1;
  BOOL hasCiphertext_:1;
  BOOL hasCounter_:1;
  BOOL hasPreviousCounter_:1;
  NSData* coreKey;
  NSData* ciphertext;
  UInt32 counter;
  UInt32 previousCounter;
}
- (BOOL) hasCoreKey;
- (BOOL) hasCounter;
- (BOOL) hasPreviousCounter;
- (BOOL) hasCiphertext;
@property (readonly, strong) NSData* coreKey;
@property (readonly) UInt32 counter;
@property (readonly) UInt32 previousCounter;
@property (readonly, strong) NSData* ciphertext;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ProtoSecretMessageBuilder*) builder;
+ (ProtoSecretMessageBuilder*) builder;
+ (ProtoSecretMessageBuilder*) builderWithPrototype:(ProtoSecretMessage*) prototype;
- (ProtoSecretMessageBuilder*) toBuilder;

+ (ProtoSecretMessage*) parseFromData:(NSData*) data;
+ (ProtoSecretMessage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProtoSecretMessage*) parseFromInputStream:(NSInputStream*) input;
+ (ProtoSecretMessage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProtoSecretMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ProtoSecretMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ProtoSecretMessageBuilder : PBGeneratedMessageBuilder {
@private
  ProtoSecretMessage* resultProtoSecretMessage;
}

- (ProtoSecretMessage*) defaultInstance;

- (ProtoSecretMessageBuilder*) clear;
- (ProtoSecretMessageBuilder*) clone;

- (ProtoSecretMessage*) build;
- (ProtoSecretMessage*) buildPartial;

- (ProtoSecretMessageBuilder*) mergeFrom:(ProtoSecretMessage*) other;
- (ProtoSecretMessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ProtoSecretMessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCoreKey;
- (NSData*) coreKey;
- (ProtoSecretMessageBuilder*) setCoreKey:(NSData*) value;
- (ProtoSecretMessageBuilder*) clearCoreKey;

- (BOOL) hasCounter;
- (UInt32) counter;
- (ProtoSecretMessageBuilder*) setCounter:(UInt32) value;
- (ProtoSecretMessageBuilder*) clearCounter;

- (BOOL) hasPreviousCounter;
- (UInt32) previousCounter;
- (ProtoSecretMessageBuilder*) setPreviousCounter:(UInt32) value;
- (ProtoSecretMessageBuilder*) clearPreviousCounter;

- (BOOL) hasCiphertext;
- (NSData*) ciphertext;
- (ProtoSecretMessageBuilder*) setCiphertext:(NSData*) value;
- (ProtoSecretMessageBuilder*) clearCiphertext;
@end

#define ProtoInitKeySecretMessage_registrationId @"registrationId"
#define ProtoInitKeySecretMessage_initKeyId @"initKeyId"
#define ProtoInitKeySecretMessage_signedInitKeyId @"signedInitKeyId"
#define ProtoInitKeySecretMessage_baseKey @"baseKey"
#define ProtoInitKeySecretMessage_identityKey @"identityKey"
#define ProtoInitKeySecretMessage_message @"message"
@interface ProtoInitKeySecretMessage : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasRegistrationId_:1;
  BOOL hasSignedInitKeyId_:1;
  BOOL hasBaseKey_:1;
  BOOL hasIdentityKey_:1;
  BOOL hasMessage_:1;
  BOOL hasInitKeyId_:1;
  NSString* registrationId;
  NSString* signedInitKeyId;
  NSData* baseKey;
  NSData* identityKey;
  NSData* message;
  UInt32 initKeyId;
}
- (BOOL) hasRegistrationId;
- (BOOL) hasInitKeyId;
- (BOOL) hasSignedInitKeyId;
- (BOOL) hasBaseKey;
- (BOOL) hasIdentityKey;
- (BOOL) hasMessage;
@property (readonly, strong) NSString* registrationId;
@property (readonly) UInt32 initKeyId;
@property (readonly, strong) NSString* signedInitKeyId;
@property (readonly, strong) NSData* baseKey;
@property (readonly, strong) NSData* identityKey;
@property (readonly, strong) NSData* message;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ProtoInitKeySecretMessageBuilder*) builder;
+ (ProtoInitKeySecretMessageBuilder*) builder;
+ (ProtoInitKeySecretMessageBuilder*) builderWithPrototype:(ProtoInitKeySecretMessage*) prototype;
- (ProtoInitKeySecretMessageBuilder*) toBuilder;

+ (ProtoInitKeySecretMessage*) parseFromData:(NSData*) data;
+ (ProtoInitKeySecretMessage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProtoInitKeySecretMessage*) parseFromInputStream:(NSInputStream*) input;
+ (ProtoInitKeySecretMessage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProtoInitKeySecretMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ProtoInitKeySecretMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ProtoInitKeySecretMessageBuilder : PBGeneratedMessageBuilder {
@private
  ProtoInitKeySecretMessage* resultProtoInitKeySecretMessage;
}

- (ProtoInitKeySecretMessage*) defaultInstance;

- (ProtoInitKeySecretMessageBuilder*) clear;
- (ProtoInitKeySecretMessageBuilder*) clone;

- (ProtoInitKeySecretMessage*) build;
- (ProtoInitKeySecretMessage*) buildPartial;

- (ProtoInitKeySecretMessageBuilder*) mergeFrom:(ProtoInitKeySecretMessage*) other;
- (ProtoInitKeySecretMessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ProtoInitKeySecretMessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasRegistrationId;
- (NSString*) registrationId;
- (ProtoInitKeySecretMessageBuilder*) setRegistrationId:(NSString*) value;
- (ProtoInitKeySecretMessageBuilder*) clearRegistrationId;

- (BOOL) hasInitKeyId;
- (UInt32) initKeyId;
- (ProtoInitKeySecretMessageBuilder*) setInitKeyId:(UInt32) value;
- (ProtoInitKeySecretMessageBuilder*) clearInitKeyId;

- (BOOL) hasSignedInitKeyId;
- (NSString*) signedInitKeyId;
- (ProtoInitKeySecretMessageBuilder*) setSignedInitKeyId:(NSString*) value;
- (ProtoInitKeySecretMessageBuilder*) clearSignedInitKeyId;

- (BOOL) hasBaseKey;
- (NSData*) baseKey;
- (ProtoInitKeySecretMessageBuilder*) setBaseKey:(NSData*) value;
- (ProtoInitKeySecretMessageBuilder*) clearBaseKey;

- (BOOL) hasIdentityKey;
- (NSData*) identityKey;
- (ProtoInitKeySecretMessageBuilder*) setIdentityKey:(NSData*) value;
- (ProtoInitKeySecretMessageBuilder*) clearIdentityKey;

- (BOOL) hasMessage;
- (NSData*) message;
- (ProtoInitKeySecretMessageBuilder*) setMessage:(NSData*) value;
- (ProtoInitKeySecretMessageBuilder*) clearMessage;
@end

#define ProtoKeyExchangeMessage_id @"id"
#define ProtoKeyExchangeMessage_baseKey @"baseKey"
#define ProtoKeyExchangeMessage_coreKey @"coreKey"
#define ProtoKeyExchangeMessage_identityKey @"identityKey"
#define ProtoKeyExchangeMessage_baseKeySignature @"baseKeySignature"
@interface ProtoKeyExchangeMessage : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasBaseKey_:1;
  BOOL hasCoreKey_:1;
  BOOL hasIdentityKey_:1;
  BOOL hasBaseKeySignature_:1;
  BOOL hasId_:1;
  NSData* baseKey;
  NSData* coreKey;
  NSData* identityKey;
  NSData* baseKeySignature;
  UInt32 id;
}
- (BOOL) hasId;
- (BOOL) hasBaseKey;
- (BOOL) hasCoreKey;
- (BOOL) hasIdentityKey;
- (BOOL) hasBaseKeySignature;
@property (readonly) UInt32 id;
@property (readonly, strong) NSData* baseKey;
@property (readonly, strong) NSData* coreKey;
@property (readonly, strong) NSData* identityKey;
@property (readonly, strong) NSData* baseKeySignature;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ProtoKeyExchangeMessageBuilder*) builder;
+ (ProtoKeyExchangeMessageBuilder*) builder;
+ (ProtoKeyExchangeMessageBuilder*) builderWithPrototype:(ProtoKeyExchangeMessage*) prototype;
- (ProtoKeyExchangeMessageBuilder*) toBuilder;

+ (ProtoKeyExchangeMessage*) parseFromData:(NSData*) data;
+ (ProtoKeyExchangeMessage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProtoKeyExchangeMessage*) parseFromInputStream:(NSInputStream*) input;
+ (ProtoKeyExchangeMessage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProtoKeyExchangeMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ProtoKeyExchangeMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ProtoKeyExchangeMessageBuilder : PBGeneratedMessageBuilder {
@private
  ProtoKeyExchangeMessage* resultProtoKeyExchangeMessage;
}

- (ProtoKeyExchangeMessage*) defaultInstance;

- (ProtoKeyExchangeMessageBuilder*) clear;
- (ProtoKeyExchangeMessageBuilder*) clone;

- (ProtoKeyExchangeMessage*) build;
- (ProtoKeyExchangeMessage*) buildPartial;

- (ProtoKeyExchangeMessageBuilder*) mergeFrom:(ProtoKeyExchangeMessage*) other;
- (ProtoKeyExchangeMessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ProtoKeyExchangeMessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (UInt32) id;
- (ProtoKeyExchangeMessageBuilder*) setId:(UInt32) value;
- (ProtoKeyExchangeMessageBuilder*) clearId;

- (BOOL) hasBaseKey;
- (NSData*) baseKey;
- (ProtoKeyExchangeMessageBuilder*) setBaseKey:(NSData*) value;
- (ProtoKeyExchangeMessageBuilder*) clearBaseKey;

- (BOOL) hasCoreKey;
- (NSData*) coreKey;
- (ProtoKeyExchangeMessageBuilder*) setCoreKey:(NSData*) value;
- (ProtoKeyExchangeMessageBuilder*) clearCoreKey;

- (BOOL) hasIdentityKey;
- (NSData*) identityKey;
- (ProtoKeyExchangeMessageBuilder*) setIdentityKey:(NSData*) value;
- (ProtoKeyExchangeMessageBuilder*) clearIdentityKey;

- (BOOL) hasBaseKeySignature;
- (NSData*) baseKeySignature;
- (ProtoKeyExchangeMessageBuilder*) setBaseKeySignature:(NSData*) value;
- (ProtoKeyExchangeMessageBuilder*) clearBaseKeySignature;
@end

#define ProtoSenderKeyMessage_id @"id"
#define ProtoSenderKeyMessage_iteration @"iteration"
#define ProtoSenderKeyMessage_ciphertext @"ciphertext"
@interface ProtoSenderKeyMessage : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasCiphertext_:1;
  BOOL hasId_:1;
  BOOL hasIteration_:1;
  NSData* ciphertext;
  UInt32 id;
  UInt32 iteration;
}
- (BOOL) hasId;
- (BOOL) hasIteration;
- (BOOL) hasCiphertext;
@property (readonly) UInt32 id;
@property (readonly) UInt32 iteration;
@property (readonly, strong) NSData* ciphertext;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ProtoSenderKeyMessageBuilder*) builder;
+ (ProtoSenderKeyMessageBuilder*) builder;
+ (ProtoSenderKeyMessageBuilder*) builderWithPrototype:(ProtoSenderKeyMessage*) prototype;
- (ProtoSenderKeyMessageBuilder*) toBuilder;

+ (ProtoSenderKeyMessage*) parseFromData:(NSData*) data;
+ (ProtoSenderKeyMessage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProtoSenderKeyMessage*) parseFromInputStream:(NSInputStream*) input;
+ (ProtoSenderKeyMessage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProtoSenderKeyMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ProtoSenderKeyMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ProtoSenderKeyMessageBuilder : PBGeneratedMessageBuilder {
@private
  ProtoSenderKeyMessage* resultProtoSenderKeyMessage;
}

- (ProtoSenderKeyMessage*) defaultInstance;

- (ProtoSenderKeyMessageBuilder*) clear;
- (ProtoSenderKeyMessageBuilder*) clone;

- (ProtoSenderKeyMessage*) build;
- (ProtoSenderKeyMessage*) buildPartial;

- (ProtoSenderKeyMessageBuilder*) mergeFrom:(ProtoSenderKeyMessage*) other;
- (ProtoSenderKeyMessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ProtoSenderKeyMessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (UInt32) id;
- (ProtoSenderKeyMessageBuilder*) setId:(UInt32) value;
- (ProtoSenderKeyMessageBuilder*) clearId;

- (BOOL) hasIteration;
- (UInt32) iteration;
- (ProtoSenderKeyMessageBuilder*) setIteration:(UInt32) value;
- (ProtoSenderKeyMessageBuilder*) clearIteration;

- (BOOL) hasCiphertext;
- (NSData*) ciphertext;
- (ProtoSenderKeyMessageBuilder*) setCiphertext:(NSData*) value;
- (ProtoSenderKeyMessageBuilder*) clearCiphertext;
@end

#define ProtoSenderKeyDistributionMessage_id @"id"
#define ProtoSenderKeyDistributionMessage_iteration @"iteration"
#define ProtoSenderKeyDistributionMessage_chainKey @"chainKey"
#define ProtoSenderKeyDistributionMessage_signingKey @"signingKey"
@interface ProtoSenderKeyDistributionMessage : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasChainKey_:1;
  BOOL hasSigningKey_:1;
  BOOL hasId_:1;
  BOOL hasIteration_:1;
  NSData* chainKey;
  NSData* signingKey;
  UInt32 id;
  UInt32 iteration;
}
- (BOOL) hasId;
- (BOOL) hasIteration;
- (BOOL) hasChainKey;
- (BOOL) hasSigningKey;
@property (readonly) UInt32 id;
@property (readonly) UInt32 iteration;
@property (readonly, strong) NSData* chainKey;
@property (readonly, strong) NSData* signingKey;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ProtoSenderKeyDistributionMessageBuilder*) builder;
+ (ProtoSenderKeyDistributionMessageBuilder*) builder;
+ (ProtoSenderKeyDistributionMessageBuilder*) builderWithPrototype:(ProtoSenderKeyDistributionMessage*) prototype;
- (ProtoSenderKeyDistributionMessageBuilder*) toBuilder;

+ (ProtoSenderKeyDistributionMessage*) parseFromData:(NSData*) data;
+ (ProtoSenderKeyDistributionMessage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProtoSenderKeyDistributionMessage*) parseFromInputStream:(NSInputStream*) input;
+ (ProtoSenderKeyDistributionMessage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProtoSenderKeyDistributionMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ProtoSenderKeyDistributionMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ProtoSenderKeyDistributionMessageBuilder : PBGeneratedMessageBuilder {
@private
  ProtoSenderKeyDistributionMessage* resultProtoSenderKeyDistributionMessage;
}

- (ProtoSenderKeyDistributionMessage*) defaultInstance;

- (ProtoSenderKeyDistributionMessageBuilder*) clear;
- (ProtoSenderKeyDistributionMessageBuilder*) clone;

- (ProtoSenderKeyDistributionMessage*) build;
- (ProtoSenderKeyDistributionMessage*) buildPartial;

- (ProtoSenderKeyDistributionMessageBuilder*) mergeFrom:(ProtoSenderKeyDistributionMessage*) other;
- (ProtoSenderKeyDistributionMessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ProtoSenderKeyDistributionMessageBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (UInt32) id;
- (ProtoSenderKeyDistributionMessageBuilder*) setId:(UInt32) value;
- (ProtoSenderKeyDistributionMessageBuilder*) clearId;

- (BOOL) hasIteration;
- (UInt32) iteration;
- (ProtoSenderKeyDistributionMessageBuilder*) setIteration:(UInt32) value;
- (ProtoSenderKeyDistributionMessageBuilder*) clearIteration;

- (BOOL) hasChainKey;
- (NSData*) chainKey;
- (ProtoSenderKeyDistributionMessageBuilder*) setChainKey:(NSData*) value;
- (ProtoSenderKeyDistributionMessageBuilder*) clearChainKey;

- (BOOL) hasSigningKey;
- (NSData*) signingKey;
- (ProtoSenderKeyDistributionMessageBuilder*) setSigningKey:(NSData*) value;
- (ProtoSenderKeyDistributionMessageBuilder*) clearSigningKey;
@end


// @@protoc_insertion_point(global_scope)
